### ISSUE TITLE
This Vs Sqlx?

### ISSUE THREAD

**Issue by codeitlikemiley** [filipton/planetscale-driver#2]
I know I can just use sqlx to query planetscale db ,

What is the difference of using this package? 

aside it uses  HTTP api of planetscale.... and the query builder you created?

Why would i use this? what use case? would it fit...
i see this is a database-js counter part in rust
which is built for serverless websites

Any performance, benchmark comparison vs http and direct db connection with sqlx?

on query builder whats difference on sqlx?

Also , why not just extend on sqlx , and build on top of it? like error handling on Vitest...

I hope I can have broader info , im highly interested on using planetscale on my next project...

and I wanna know if just sqlx if enough and do i need to use this package (if recommended)

thanks

**Comment by filipton** [comment]
> I know I can just use sqlx to query planetscale db ,
> 
> What is the difference of using this package?
> 
> aside it uses HTTP api of planetscale.... and the query builder you created?
> 
Soo my crate has much less features than SQLX, and it only supports planetscale.

> Why would i use this? what use case? would it fit... i see this is a database-js counter part in rust which is built for serverless websites
> 
Yep, like the database-js its only viable to use this on serverless - i don't see any reason to use it outside the serverless environment. So if you aren't making a serverless website i think you should look somewhere else (SQLX).

> Any performance, benchmark comparison vs http and direct db connection with sqlx?
> 
I don't have any, but i can say that accessing DB through HTTP API would be much slower then "raw" db connection with sqlx (http connection establishment for each query)

> on query builder whats difference on sqlx?
> 
My querybuilder does simple "find and replace" - it looks for `$X` sequences, gets index (X) and then just replaces it with bounded variable (these variables are escaped). I don't think SQLX does that in any different way but i might be wrong.

> Also , why not just extend on sqlx , and build on top of it? like error handling on Vitest...
> 
I think it would took too much time for that nich usecase (maybe it isn't nich - idk)

> I hope I can have broader info , im highly interested on using planetscale on my next project...
> 
> and I wanna know if just sqlx if enough and do i need to use this package (if recommended)
> 
As i mentioned above, if you aren't using serverless this crate is useless for you. SQLX is enough for you if you are planning to deploy your app on for example bare-metal (planetscale is mysql compatiable)

I hope i brighten to you use case of this crate, and now you know what will you use for your project :D
